### ISSUE TITLE
[bug] Ошибка открытия ссылки из КМ

### ISSUE THREAD

**Issue by Psychosoc1al** [luntikius/BetterOrioks#14]
При попытке открыть некоторые ссылки из ресурсов конкретных контрольных мероприятий, в частности, ведущие на 
- [тест в Moodle один](https://orioks.miet.ru/mdl-gateway/quiz/4907#) и
- [тест в Moodle два](https://orioks.miet.ru/mdl-gateway/quiz/3760#&idKM=1409133&debt=0)

вылезает ["Произошла ошибка при открытии файла, возможно..."](https://github.com/luntikius/BetterOrioks/blob/76172ce883fff815050c0f56a5bc61c5409407a5/app/src/main/res/values/strings.xml#L86)

Поскольку [вот такая ссылка](http://www.psyworld.info/online-testy/test-belbina) открывается без проблем, подозреваю, дело может быть в якоре (или как там `#` называется) в тексте ссылки

**Comment by luntikius** [comment]
Это да, это починю.
