### ISSUE TITLE
[enhancement] Обработка бонусных баллов

### ISSUE THREAD

**Issue by Psychosoc1al** [luntikius/BetterOrioks#15]
Суть в следующем: контрольные мероприятия, которые не входят в стандартную сотню баллов (зелёные, они же `"bonus": 1` в данных КМ), тоже учитываются в подсчёте общей суммы, и потому иногда получается что-то вроде:

<img src="https://github.com/luntikius/BetterOrioks/assets/63284142/e4ebcbab-9dc3-46e0-a071-a51e3fb86375" width=400>

Моя перфекционистская натура не может переварить выделенные красным 94 балла, да и вот это `из 499` смотрится как будто странно)
Дело вкуса, возможно: мне больше нравится подход, когда может быть `120 из 100`, как в веб-версии, собственно, ОРИОКС, и "лишние" баллы идут только в текущую сумму

Итак, лаконичные предложения:
- выбор цвета покраски баллов в стандартном соотношении (20, 50, 70, 86 баллов как реперные точки)
- ограничение суммы баллов суммой по обязательным мероприятиям (то есть сотней)

**Comment by luntikius** [comment]
Звучит логично. У меня таких дисциплин не было, поэтому не видел, что так бывает. Подумаю, что можно с этим сделать.
