### ISSUE TITLE
[enhancement] Отображение дисциплин с обычным зачётом

### ISSUE THREAD

**Issue by Psychosoc1al** [luntikius/BetterOrioks#16]
Поскольку у зачётных дисциплин, по сути, всего два состояния:
- `незачёт`, что соответствует `неудовлетворительно` (менее двадцати баллов)
- `зачёт`, что так явно не транслируешь, но по сути &mdash; `отлично`, ведь после половины баллов тоже уже как бы делать что-то ещё нет смысла с точки зрения оценки

Потому само предложение: определять положение зачётных дисциплин при сортировке по оценке не количеством баллов, а по "состоянием": отправлять либо в `неудовлетворительно`, либо в `отлично` или отдельный раздел, например

**Comment by luntikius** [comment]
Это не совсем корректно. Если хочешь выйти на стипендию или перевестись с платного обучения на бесплатное, тебе важно, какой у тебя результат по зачетной дисциплине.

**Comment by Psychosoc1al** [comment]
> Если хочешь выйти на стипендию или перевестись с платного обучения на бесплатное

Отвечу консервативно — сам не переводился, но стипендию за «отлично» с 52-мя баллами по физкультуре имею, — по крайней мере, в плане стипендии точно могу сказать, что не влияет)

Ну в целом это как будто логично, [вот тут пункт 2.1](https://www.miet.ru/upload/content/UVK/Polozhenie_o_stipendialnom_obespechenii_2022.pdf)
