### ISSUE TITLE
[bug] Сломанные ссылки новостей

### ISSUE THREAD

**Issue by Psychosoc1al** [luntikius/BetterOrioks#17]
Обнаружил следующий баг: при попытке открыть новость из соответствующего списка открывается битая ссылка вида `https://orioks.miet.ru/https://orioks.miet.ru/main/...`

В общем, дважды добавляется префикс, насколько я понимаю, [здесь](https://github.com/luntikius/BetterOrioks/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fstudentapp%2Fbetterorioks%2Fdata%2FOrioksRepository.kt#L188) и [вот тут](https://github.com/luntikius/BetterOrioks/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fstudentapp%2Fbetterorioks%2Fui%2Fscreens%2FProfileScreen.kt#L184).
В общем, мелочи)

**Comment by luntikius** [comment]
Интересно, похоже они поменяли ориокс, раньше приходил только конец ссылки. Спасибо за замечание, исправлю.

**Comment by luntikius** [comment]
А нет, удивительно, действительно два раза префикс, не помню, что-бы я такое добавлял, видимо деменция. Все починил.

**Comment by Psychosoc1al** [comment]
Ну и так, в качестве постскриптума, уж извиняюсь, что под конец года навалил всякого сюда)0)

А вообще спасибо за классное приложение и отличную работу, с наступающим)
